# Which agentic-lib workflow schedule should be used?
schedule: schedule-3
featuresWipLimit: 3
featureDevelopmentIssuesWipLimit: 6
maintenanceIssuesWipLimit: 2
attemptsPerBranch: 4
attemptsPerIssue: 2
