# Which agentic-lib workflow schedule should be used?
schedule: schedule-3
sourcesLimit: 1000
documentsLimit: 1000
featuresWipLimit: 6
featureDevelopmentIssuesWipLimit: 6
maintenanceIssuesWipLimit: 2
attemptsPerBranch: 2
attemptsPerIssue: 2
