# Which agentic-lib workflow schedule should be used?
schedule: schedule-2
sourcesLimit: 8
documentsLimit: 128
featuresWipLimit: 6
featureDevelopmentIssuesWipLimit: 6
maintenanceIssuesWipLimit: 2
attemptsPerBranch: 2
attemptsPerIssue: 2
writeableFilepaths:
  docs:         "docs/"
  features:     "features/"
  library:      "library/"
  src:          "src/lib/"
  tests:        "tests/unit/"
  dependencies: "package.json"
  readme:       "README.md"
  sources:      "SOURCES*.md"
